language: python
jobs:
  include:
    - name: "Python 3.9 on Focal Linux"
      os: linux
      dist: focal
      python: 3.9
install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade pyinstaller
script:
  - pyinstaller cisco-config-tftp.py --onefile
